# Generated by Django 5.2.6 on 2025-10-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_chasis_number_customer_engine_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installment',
            old_name='date',
            new_name='installment_date',
        ),
        migrations.AddField(
            model_name='installment',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='balance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
