# Generated by Django 5.2.6 on 2025-10-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_date_installment_installment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='emi_day',
            field=models.PositiveSmallIntegerField(default=5, help_text='Fixed EMI day each month (1-28)'),
        ),
    ]
