# Generated by Django 5.2.6 on 2025-10-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_name_customer_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
